# Generated by Django 5.2.7 on 2025-11-05 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_rating_parent_alter_moments_movie_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='text_ru',
        ),
        migrations.AlterField(
            model_name='rating',
            name='stars',
            field=models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')]),
        ),
    ]
